# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-16 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(related_name='movie_actors', through='mrs.Role', to='mrs.Person'),
        ),
    ]
